services:
  redis:
    image: 'bitnamilegacy/redis:8.2.1'
    networks:
      - hmpps
    container_name: wmt-web-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  hmpps-auth:
    image: ghcr.io/ministryofjustice/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev,delius
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - DELIUS_ENABLED=true
      - DELIUS_ENDPOINT_URL=http://wiremock:8099
      - MANAGE_USERS_API_ENABLED=true
      - MANAGE_USERS_API_ENDPOINT_URL=http://hmpps-manage-users-api:8080
    depends_on:
      - "wiremock"
      - "manage-users-wiremock"
      - "postgres"

  manage-users-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps
    restart: always
    ports:
      - "9096:8080"
  hmpps-manage-users-api:
    image: ghcr.io/ministryofjustice/hmpps-manage-users-api:latest
    networks:
      - hmpps
    container_name: hmpps-manage-users-api
    ports:
      - "9091:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,delius
      - HMPPS-AUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - AUTHORIZATION-SERVER_TOKEN_ENDPOINT_URL=http://hmpps-auth:8080/auth/oauth/token
      - EXTERNAL-USERS_ENDPOINT_URL=http://hmpps-external-users-api:8080
      - DELIUS_ENDPOINT_URL=http://wiremock:8099
    depends_on:
      - "hmpps-auth"
      - "wiremock"
      - "postgres"

  hmpps-external-users-api:
    image: ghcr.io/ministryofjustice/hmpps-external-users-api:latest
    container_name: hmpps-external-users-api
    depends_on:
      - hmpps-auth
    ports:
      - "8088:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,local-postgres
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth
      - SPRING_R2DBC_URL=r2dbc:postgresql://auth-db:5432/auth-db?sslmode=verify-full
      - SPRING_FLYWAY_URL=jdbc:postgresql://auth-db:5432/auth-db?sslmode=verify-full

  allocations-service:
    image: quay.io/hmpps/hmpps-allocations
    container_name: allocations-service
    ports:
      - "8091:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - "postgres"

  hmpps-workload:
    image: quay.io/hmpps/hmpps-workload:latest
    networks:
      - hmpps
    container_name: wmt-web-hmpps-workload
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,docker
      - DATABASE_ENDPOINT=postgres:5432
      - COMMUNITY_ENDPOINT_URL=http://wiremock:8099
      - HMPPS_TIER_ENDPOINT_URL=http://wiremock:8099
      - HMPPS_SQS_LOCALSTACK_URL=http://localstack:4566
    entrypoint: ["/bin/sh", "-c" , "sleep 10 && java -javaagent:/app/agent.jar -jar /app/app.jar"]
    depends_on:
      - "postgres"
      - "wiremock"
      - "localstack"

  postgres:
    image: postgres:14
    networks:
      - hmpps
    container_name: wmt-web-hmpps-workload-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=root

  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: wiremock
    restart: always
    ports:
      - "8099:8099"
    command: ["--port","8099","--global-response-templating"]
  localstack:
    image: localstack/localstack:4.14
    networks:
      - hmpps
    container_name: wmt-web-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - 8999:8080
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - $PWD/test/integration/resources:/docker-entrypoint-initaws.d
networks:
  hmpps:
